title = "anno config"

# This is for processing the "combine" case (where all annotation data is in one file) when generating an MDA file. You can configure one or more annotation data with the following parameters:

# id: the name of the annotation data. If not specified, the file name of the annotation data will be used as the ID.
# path (required): the file path of the annotation data.
# start: the line number to start reading from in the annotation data file. If not specified, it will start from the first line.
# end: the line number to stop reading from in the annotation data file. If not specified, it will read until the end of the file.


[[annotation]]
id = "identify"
path = "test/anno/identity_CelebA.txt"
start = 1
end=1001

[[annotation]]
path = "test/anno/list_attr_celeba.txt"
start = 3
end=1002

[[annotation]]
path = "test/anno/list_bbox_celeba.txt"
start = 3
end=1002

[[annotation]]
id = "landmarks"
path = "test/anno/list_landmarks_celeba.txt"
start=3
end=1002
